[phases.setup]
nixPkgs = ["python311", "pip", "uvicorn"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --lifespan off"
